import Image from 'next/image'
import Head from 'next/head'
import { Inter } from 'next/font/google'
import About from '../../Components/About'
import Skill from '../../Components/Skill'
import Projects from '../../Components/Projects'
import { BsGithub } from 'react-icons/bs'
import { BsFillFileEarmarkPdfFill } from 'react-icons/bs'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home(props) {
  return (
    <>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="%PUBLIC_URL%/logonada.png" />
        <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet"></link>
        <link rel="stylesheet" href="/path/to/folder/css/academicons.min.css" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css"></link>



      </Head>
      <div className=''>

        <About />
        <Skill />

        {/* ****************** projects ***************/}
        <div id="project" className='container mx-auto  text-start sm:h-screen'>
          <div className='grid  grid-cols-1  sm:grid-cols-3 px-5 py-16  mt-10 sm:grid-flow-col gap-4'>
            <div>
              <h1 className='font-bold  font-serif'>Projects</h1>
            </div>
            <div className='flex flex-col col-span-2 gap-4  pt-5'>
              {props.posts.map(post => (
                <Link href={`/${post.id}`} key={post.id}>

                  <div className='text-start mt-2'>
                    <h2 className='font-bold text-2xl font-bold  text-cyan-600 hover:underline cursor-pointer'>{post.title}</h2>
                    <p className='text-base'>{post.body}</p>
                    <div className='flex flex-row gap-2 mt-5'>
                      <Link href={`${post.pdf}`}>
                        <button className='relative  rounded-lg border border-cyan-600 p-1 px-2  flex flex-row gap-1 '>
                          <BsFillFileEarmarkPdfFill style={{ color: "#0891b2" }} className='hover:color-white' />
                          <h6 className='text-cyan-600 text-xs'>PDF</h6>
                        </button>
                      </Link>
                      <Link href={`${post.code}`}>
                        <button className='relative  rounded-lg border border-cyan-600 p-1 px-2 flex flex-row gap-1  '>
                          <BsGithub style={{ color: "#0891b2" }} />
                          <h6 className='text-cyan-600 text-xs'>Code</h6>
                        </button>
                      </Link>
                      <Link href={`${post.poster}`}>
                        <button className='relative  rounded-lg border border-cyan-600 p-1  px-2 flex flex-row gap-1  '>

                          <h6 className='text-cyan-600 text-xs'>Poster</h6>
                        </button>
                      </Link>
                    </div>
                  </div>

                </Link>
              ))}
            </div>
          </div>
        </div >
        {/* end project */}



      </div>


    </>

  )
}

export const getStaticProps = async () => {
  const res = await fetch("https://jsonplaceholder.typicode.com/posts?_limit=2");
  const data = await res.json();

  return {
    props: {
      posts: data
    }
  }
}


